web_app/__init__.py
from flask import Flask
from datetime import timedelta
from models import storage

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'polling_unit_app'

    from web_app.routes import views
    app.register_blueprint(views, url_prefix='/')

    return app

def configure_db(app):
    with app.app_context():
        storage.reload()
    return app

web_app/app.py
from web_app import create_app, configure_db


app = create_app()
configure_db(app)  # Call the configure_db function

if __name__ == "__main__":
    app.run(port=5001, debug=True)

web_app/routes.py
from flask import Blueprint, render_template, request, jsonify, url_for, flash, redirect
from models import storage
from models.new_result import Result

views = Blueprint('route', __name__)
"""Define the global variable to store selected LGAs"""
selected_lgas = []

@views.route('/')
def home():
    polling_unit = storage.get_polling_unit()
    return render_template('index.html', title='Polling Unit', polling_units=polling_unit)

@views.route('/polling_unit/<int:polling_unit_id>')
def polling_unit(polling_unit_id):
    polling_unit = storage.get_polling_unit_by_id(polling_unit_id)
    unit_name = polling_unit.polling_unit_name
    polling_unit_results = storage.get_polling_unit_results(polling_unit_id)
    return render_template('result.html', title='Polling Unit Result', 
                           polling_unit_results=polling_unit_results,
                           polling_unit_name=unit_name)


@views.route('/summed_results', methods=['GET', 'POST'])
def summed_results():
    global selected_lgas
    if request.method == 'POST':
        selected_lgas = request.get_json().get('selected_lgas', [])

        redirect_url = url_for('route.summed_results_data')
        """redirect page"""
        response_data = {
            'redirect_url': redirect_url
        }
        """Return the summed results as JSON"""
        return jsonify({'data': response_data})
    
    lga = storage.get_lga()
    return render_template('summed_results.html', title='Summed Result', 
                           local_governments=lga)

@views.route('/summed_results_data', methods=['GET'])
def summed_results_data():
    """Query the database to fetch the polling units in the selected local government"""
    polling_units = storage.get_polling_units_by_ids(selected_lgas)

    """Initialize a dictionary to store summed results for each party"""
    summed_results = {}

    """Loop through each polling unit and sum the results for each party"""
    for polling_unit in polling_units:

        polling_unit_id = polling_unit.uniqueid
        results = storage.get_polling_unit_results(polling_unit_id)

        """Sum the results for each party"""
        for result in results:
            party_abbreviation = result.party_abbreviation
            party_score = result.party_score

            """Add or update the party's total score in the summed_results dictionary"""
            if party_abbreviation in summed_results:
                summed_results[party_abbreviation] += party_score
            else:
                summed_results[party_abbreviation] = party_score
    return render_template('summed_results_data.html', title='Summed Result Data for All LGAs', summed_results=summed_results)

@views.route('/new_result', methods=['GET', 'POST'])
def new_result():
    parties = storage.get_parties()
    if request.method == 'POST':
        """Loop through the parties to extract results"""
        polling_unit_name = request.form.get('polling_unit_name')
        pdp = int(request.form.get('PDP'))
        dpp = int(request.form.get('DPP'))
        acn = int(request.form.get('ACN'))
        ppa = int(request.form.get('PPA'))
        cdc = int(request.form.get('CDC'))
        jp = int(request.form.get('JP'))
        anpp = int(request.form.get('ANPP'))
        labour = int(request.form.get('LABOUR'))
        cpp = int(request.form.get('CPP'))

        result = Result(
            polling_unit_name=polling_unit_name,
            pdp=pdp,
            dpp=dpp,
            acn=acn,
            ppa=ppa,
            cdc=cdc,
            jp=jp,
            anpp=anpp,
            labour=labour,
            cpp=cpp
        )
        """Add the new_result to the database"""
        storage.new(result)
        storage.save()
        flash('New Entry Saved Successfully', category='success')
        return redirect(url_for('route.new_result'))
    return render_template('store_new_result.html', title='Store New Result', parties=parties)

web_app/templates/_message.html
{% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'success' %}
                <div class="ui success message">
                    <i class="close icon"></i>
                    <div class="header">
                    {{ message }}
                    </div>
                </div>
            {% else %}
                <div class="ui negative message">
                    <i class="close icon"></i>
                    <div class="header">
                    {{ message }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

web_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.js"></script>
    {% block summed_result %}{% endblock %}
</body>
</html>

web_app/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block body %}
<div class="ui container fluid">
    <h3 class="ui block header">
        {{ title }}
    </h3>
</div><br>
<div class="ui container fluid">
    <table class="ui orange celled striped table">
        <thead class="full-width">
            <tr>
                <th colspan="5">
                    <a href="{{ url_for('route.summed_results')}}">
                        <div class="ui right floated small primary button">
                            Collate
                        </div>
                    </a>
                    {{ title }}
                    <a href="{{ url_for('route.new_result')}}">
                        <div class="ui small teal button">
                            Enter New Result
                        </div>
                    </a>
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>Sn</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Entered</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for polling_unit in polling_units %}
            <a href="#" class="">
                <tr>
                    <td class="one width">{{ loop.index }}</td>
                    <td>{{ polling_unit.polling_unit_name }}</td>
                    <td>{{ polling_unit.polling_unit_description }}</td>
                    <td>{{ polling_unit.date_entered }}</td>
                    <td data-label="status">
                        <div class="ui buttons">
                            <a href="{{ url_for('route.polling_unit', polling_unit_id=polling_unit.polling_unit_id) }}"><button class="ui positive button active update-task-button">View</button></a>
                        </div>
                    </td>
                </tr>
            </a>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

web_app/templates/result.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="ui container fluid">
    <h3 class="ui block header">
        {{ title }} ( {{ polling_unit_name }} )
    </h3>
</div><br>
<div class="ui container fluid">
    <table class="ui orange celled striped table">
        <thead>
            <tr>
                <th colspan="5">
                    <a href="{{ url_for('route.home')}}">
                        <div class="ui small primary button">
                            Back to Home
                        </div>
                    </a>
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>Sn</th>
                <th>Party Abbreviation</th>
                <th>Party Score</th>
                <th>Date Entered</th>
                <th>Entered By</th>
            </tr>
        </thead>
        <tbody>
            {% if polling_unit_results %}
                {% for result in polling_unit_results %}
                <tr>
                    <td class="one width">{{ loop.index }}</td>
                    <td>{{ result.party_abbreviation }}</td>
                    <td>{{ result.party_score }}</td>
                    <td>{{ result.date_entered.strftime('%b %d, %Y at %H:%M') }}</td>
                    <td>{{ result.entered_by_user }}</td> 
                </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td class="one width">No Result for this selection! </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

web_app/templates/store_new_result.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="ui container fluid">
    <h3 class="ui block header">
        {{ title }}
    </h3>
    <div class="ui buttons">
        <a href="{{ url_for('route.home') }}">
            <button class="ui right floated teal button">
                Home Page
            </button>
        </a>
    </div>
</div><br>
<div class="ui container">
    <div class="column mystyle" style="min-width: 70%;">
    {% include '_message.html' %}
        <h2 class="ui teal header">
            <div class="content">
            Register Result for a New Polling Unit
            </div>
        </h2>
        <form class="ui large form" method="POST", action="{{ url_for('route.new_result') }}">
            <div class="ui stacked segment">
            <div class="field">
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input type="text" name="polling_unit_name" placeholder="Polling Unit Name" required>
                </div>
            </div>
            <h4 class="dividing header">Results for Parties:</h4>
            <div class="two fields">
                {% for party in parties %}
                <div class="field">
                    <label for="{{ party.partyid }}">{{ party.partyname}}</label> 
                    <input type="number" name="{{ party.partyid }}" placeholder="Enter Result">
                </div>
                {% endfor %}
            </div>
            <input type="submit" class="ui fluid large teal submit button">
            </div>
        </form>
    </div>
</div>
{% endblock %}

web_app/templates/summed_results.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block body %}
<div class="ui container fluid">
    <h3 class="ui block header">
        {{ title }}
    </h3>
</div><br>
<div class="ui container fluid">
    <table class="ui orange compact celled definition table">
        <thead class="full-width">
            <tr>
                <th></th>
                <th colspan="4">
                    <div class="ui right floated small primary labeled icon button" id="select-lgas-button">
                    <i class="checkmark icon"></i> Sum Result
                    </div>
                    <div class="ui small teal button" id="select_all">
                    Select All
                    </div>
                    <a href="{{ url_for('route.home')}}">
                        <div class="ui small primary button">
                            Back to Home
                        </div>
                    </a>
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th></th>
                <th>Sn</th>
                <th>LGA Name</th>
                <th>LGA Description</th>
            </tr>
        </thead>
        <tbody>
            {% for lga in local_governments %}
            <tr>
                <td class="collapsing">
                    <div class="ui fitted slider checkbox">
                        <input type="checkbox" class="lga-checkbox" data-id="{{ lga.lga_id }}">
                        <label></label>
                    </div>
                </td>
                <td>{{ loop.index }}</td>
                <td>{{ lga.lga_name }}</td>
                <td>{{ lga.lga_description }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table><br>
</div><br>
{% endblock %}
{% block summed_result %}
<script src="{{ url_for('static', filename='scripts/summed_result.js')  }}"></script>
{% endblock %}

web_app/templates/summed_results_data.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block body %}
<div class="ui container fluid">
    <h3 class="ui block header">
        {{ title }}
    </h3>
</div><br>
<div class="ui container fluid">
    <table id="results-table" class="ui green celled striped table">
        <thead>
            <tr>
                <th colspan="3">
                    RESULT
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>S/n</th>
                <th>Party</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% if summed_results %}
            {% for party, result in summed_results.items() %}
                <tr>
                    <td style="width: 100px;">{{ loop.index }}</td>
                    <td>{{ party }}</td>
                    <td>{{ result }}</td>
                </tr>
            {% endfor %}
            {% else %}
            {% endif %}
        </tbody>
        <tfoot>
            <a href="#" class="">
                <tr>
                    <td data-label="status">
                        <div class="ui buttons">
                            <a href="{{ url_for('route.summed_results') }}">
                                <button class="ui positive button active">
                                    Back
                                </button>
                            </a>
                        </div>
                    </td>
                </tr>
            </a>
        </tfoot>
    </table>
</div><br>
{% endblock %}